resources:
- all.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - cacerts-coord
  name: cacerts-coord
- files:
  - cacerts-work
  name: cacerts-work
secretGenerator:
- files:
  - minio.properties
  - tpcds.properties
  - tpch.properties
  name: catalog-minio
- files:
  - public.crt
  name: ca-minio
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: volumes-coord.yaml -n argocd
- patch: volumes-work.yaml -n argocd
- patch: svc.yaml -n argocd
