resources:
  - all.yaml
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - volumes-coord.yaml -n argocd
  - volumes-work.yaml -n argocd
  - svc.yaml -n argocd
configMapGenerator:
  - name: cacerts-coord
    files:
      - cacerts-coord
  - name: cacerts-work
    files:
      - cacerts-work
secretGenerator:
  - name: catalog-minio
    files:
      - minio.properties
      - tpcds.properties
      - tpch.properties
  - name: ca-minio
    files:
      - public.crt
