apiVersion: v1
kind: Service
metadata:
  name: trino
  labels:
    app: trino
    chart: trino-0.13.0
    release: trino
    heritage: Helm
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      nodePort: 30006
      protocol: TCP
      name: http
  selector:
    app: trino
    release: trino
    component: coordinator
